// Целевые endpoint-ы по актуальному концепту (PDF),
// текущий локальный back не является источником истины.
export const apiEndpoints = {
  auth: {
    register: '/auth/register',
    verifyEmail: '/auth/verify-email',
    login: '/auth/login',
    tgLogin: '/auth/tg-login',
    tgLink: '/auth/tg-link',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
  },
  users: {
    me: '/users/me',
    patchMe: '/users/me',
    profileByUsername: (username: string) => `/users/${encodeURIComponent(username)}`,
    notifications: '/users/notifications',
  },
  cities: {
    list: '/cities',
    create: '/cities',
    byId: (cityId: string) => `/cities/${encodeURIComponent(cityId)}`,
    update: (cityId: string) => `/cities/${encodeURIComponent(cityId)}`,
    delete: (cityId: string) => `/cities/${encodeURIComponent(cityId)}`,
  },
  artists: {
    list: '/artists',
    create: '/artists',
    byId: (artistId: string | number) => `/artists/${encodeURIComponent(String(artistId))}`,
    update: (artistId: string | number) => `/artists/${encodeURIComponent(String(artistId))}`,
    deleteSoft: (artistId: string | number) => `/artists-soft/${encodeURIComponent(String(artistId))}`,
    deleteHard: (artistId: string | number) => `/artists-hard/${encodeURIComponent(String(artistId))}`,
    restore: (artistId: string | number) => `/artists/${encodeURIComponent(String(artistId))}/restore`,
  },
  venues: {
    list: '/venues',
    create: '/venues',
    byId: (venueId: string | number) => `/venues/${encodeURIComponent(String(venueId))}`,
    update: (venueId: string | number) => `/venues/${encodeURIComponent(String(venueId))}`,
    deleteSoft: (venueId: string | number) => `/venues-soft/${encodeURIComponent(String(venueId))}`,
    deleteHard: (venueId: string | number) => `/venues-hard/${encodeURIComponent(String(venueId))}`,
    restore: (venueId: string | number) => `/venues/${encodeURIComponent(String(venueId))}/restore`,
  },
  concerts: {
    list: '/concerts',
    byId: (concertId: string) => `/concerts/${encodeURIComponent(concertId)}`,
    suggest: '/concerts/suggest',
  },
  stats: {
    global: '/stats/global',
  },
  reviews: {
    list: '/review',
    byId: (reviewId: string) => `/review/${encodeURIComponent(reviewId)}`,
    create: '/review',
    likeToggle: (reviewId: string) => `/review/${encodeURIComponent(reviewId)}/like`,
    likers: (reviewId: string) => `/review/${encodeURIComponent(reviewId)}/like`,
    presignUpload: '/media/presign',
  },
  favorites: {
    list: '/favorites',
    create: '/favorites',
    remove: (targetId: string) => `/favorites/${encodeURIComponent(targetId)}`,
  },
  admin: {
    users: '/admin/users',
    pendingReviews: '/admin/review',
    approveReview: (reviewId: string) => `/review/${encodeURIComponent(reviewId)}/approve`,
    rejectReview: (reviewId: string) => `/review/${encodeURIComponent(reviewId)}/reject`,
    returnReviewToPending: (reviewId: string) => `/review/${encodeURIComponent(reviewId)}/pending`,
    pendingProfiles: '/admin/profiles/pending',
    resolveProfile: (moderationId: string) => `/admin/profiles/${encodeURIComponent(moderationId)}/resolve`,
    artists: '/admin/artists',
    artistById: (artistId: string | number) => `/admin/artists/${encodeURIComponent(String(artistId))}`,
    venues: '/admin/venues',
    venueById: (venueId: string) => `/admin/venues/${encodeURIComponent(venueId)}`,
    concerts: '/admin/concerts',
    concertById: (concertId: string) => `/admin/concerts/${encodeURIComponent(concertId)}`,
    concertRestore: (concertId: string) => `/admin/concerts/${encodeURIComponent(concertId)}/restore`,
    concertDeleteSoft: (concertId: string) => `/admin/concerts-soft/${encodeURIComponent(concertId)}`,
    concertDeleteHard: (concertId: string) => `/admin/concerts-hard/${encodeURIComponent(concertId)}`,
    concertArtists: (concertId: string) => `/admin/concerts/${encodeURIComponent(concertId)}/artists`,
    concertArtistById: (concertId: string, artistId: string | number) =>
      `/admin/concerts/${encodeURIComponent(concertId)}/artists/${encodeURIComponent(String(artistId))}`,
    concertSuggestions: '/admin/concerts/suggestions',
    concertSuggestionById: (suggestionId: string) => `/admin/concerts/suggestions/${encodeURIComponent(suggestionId)}`,
    banUser: (userId: string) => `/admin/users/${encodeURIComponent(userId)}/ban`,
    userRole: (userId: string) => `/admin/users/${encodeURIComponent(userId)}/role`,
    logs: '/admin/logs',
  },
} as const
