-- +goose Up
-- +goose StatementBegin

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT NOT NULL,

    username VARCHAR(32) NULL,
    first_name VARCHAR(64) NOT NULL DEFAULT '',
    last_name VARCHAR(64) NULL,

    avatar_url VARCHAR(255) NULL,

    is_admin BOOLEAN NOT NULL DEFAULT FALSE,

    total_reviews INTEGER NOT NULL DEFAULT 0,
    is_banned BOOLEAN NOT NULL DEFAULT FALSE,
    ban_reason TEXT NOT NULL DEFAULT '',

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS users_telegram_id_uq ON users (telegram_id);
CREATE INDEX IF NOT EXISTS users_deleted_at_idx ON users (deleted_at);


CREATE TABLE IF NOT EXISTS artists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    image_url VARCHAR(255) NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS artists_name_uq ON artists (name);
CREATE INDEX IF NOT EXISTS artists_deleted_at_idx ON artists (deleted_at);


CREATE TABLE IF NOT EXISTS venues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    address TEXT NOT NULL DEFAULT '',
    links TEXT NOT NULL DEFAULT '',
    capacity INTEGER NULL,
    description TEXT NOT NULL DEFAULT '',
    image_url VARCHAR(512) NULL,
    coordinates VARCHAR(255) NULL,
    website_url VARCHAR(512) NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS venues_deleted_at_idx ON venues (deleted_at);


CREATE TABLE IF NOT EXISTS concerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title VARCHAR(255) NULL,

    venue_id BIGINT NOT NULL,

    ticket_price_min INTEGER NOT NULL DEFAULT 0,
    ticket_price_max INTEGER NOT NULL DEFAULT 0,

    poster_url VARCHAR(255) NULL,
    description TEXT NOT NULL DEFAULT '',
    website_url VARCHAR(255) NULL,

    starts_at TIMESTAMPTZ NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ NULL,

    CONSTRAINT concerts_venue_id_fk
        FOREIGN KEY (venue_id)
        REFERENCES venues (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS concerts_venue_id_idx ON concerts (venue_id);
CREATE INDEX IF NOT EXISTS concerts_starts_at_idx ON concerts (starts_at);
CREATE INDEX IF NOT EXISTS concerts_deleted_at_idx ON concerts (deleted_at);


CREATE TABLE IF NOT EXISTS concert_artists (
    artist_id BIGINT NOT NULL,
    concert_id BIGINT NOT NULL,

    role VARCHAR(64) NOT NULL DEFAULT '',

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (artist_id, concert_id),

    CONSTRAINT concert_artists_artist_id_fk
        FOREIGN KEY (artist_id)
        REFERENCES artists (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT concert_artists_concert_id_fk
        FOREIGN KEY (concert_id)
        REFERENCES concerts (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS concert_artists_concert_id_idx ON concert_artists (concert_id);


CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,
    concert_id BIGINT NOT NULL,

    name VARCHAR(255) NOT NULL DEFAULT '',
    text TEXT NOT NULL DEFAULT '',

    media_urls TEXT[] NOT NULL DEFAULT '{}',

    execution_rating INTEGER NOT NULL DEFAULT 0,
    setlist_dynamics_rating INTEGER NOT NULL DEFAULT 0,
    crowd_interaction_rating INTEGER NOT NULL DEFAULT 0,
    sound_engineer_rating INTEGER NOT NULL DEFAULT 0,
    vibe_rating INTEGER NOT NULL DEFAULT 0,
    score INTEGER NOT NULL DEFAULT 0,

    moderation_status VARCHAR(32) NOT NULL DEFAULT 'pending',
    moderation_reason TEXT NOT NULL DEFAULT '',

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ NULL,

    CONSTRAINT reviews_user_id_fk
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT reviews_concert_id_fk
        FOREIGN KEY (concert_id)
        REFERENCES concerts (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT reviews_moderation_status_chk
        CHECK (moderation_status IN ('pending', 'approved', 'rejected'))
);

CREATE INDEX IF NOT EXISTS reviews_user_id_idx ON reviews (user_id);
CREATE INDEX IF NOT EXISTS reviews_concert_id_idx ON reviews (concert_id);
CREATE INDEX IF NOT EXISTS reviews_score_idx ON reviews (score);
CREATE INDEX IF NOT EXISTS reviews_moderation_status_idx ON reviews (moderation_status);
CREATE INDEX IF NOT EXISTS reviews_created_at_idx ON reviews (created_at);
CREATE INDEX IF NOT EXISTS reviews_deleted_at_idx ON reviews (deleted_at);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS concert_artists;
DROP TABLE IF EXISTS concerts;
DROP TABLE IF EXISTS venues;
DROP TABLE IF EXISTS artists;
DROP TABLE IF EXISTS users;

-- +goose StatementEnd
